# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d5361a8fdd3c5a28961bda692e2eb3fe153164b1cb9101aac5832467f09c4c42280c0a9f2b6af7ef2a8756ad6e957c4357cd24021e1e80dc2c4a1591010d93ce

test:
  secret_key_base: c5715185c45b864f59ea5850045cad5c334d2a1d407c1e0bdd5c982a5df892541552687c18ba526136372453c817d59a6f76e2e014458ee0ce89e948e96f384c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
